version: '3.8'

services:
  delivery_db:
    image: postgres:13-alpine
    container_name: delivery_db
    environment:
      POSTGRES_SERVER: ${POSTGRES_SERVER}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_OUTER_PORT}:${POSTGRES_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis_jobs_broker:
    image: redis:latest
    container_name: jobs_broker
    restart: always
    command: redis-server --loglevel warning
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - ./redisdata:/data
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_DATABASES=16
    env_file:
      - .env


volumes:
  pgdata:
    driver: local